# Build stage
From mcr.microsoft.com/dotnet/aspnet:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o /app
# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "qlthucung.dll"]
env:
  GOOGLE_APPLICATION_CREDENTIALS: qlthucung/credentials.json
