# ========================
# Build stage
# ========================
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /app

# ========================
# Runtime stage
# ========================
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Set environment variable for Google credentials
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

COPY --from=build /app .

ENTRYPOINT ["dotnet", "qlthucung.dll"]
